apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  namespace: services
  labels:
    app: authentication
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentication  # Bu pod label'ı
  template:
    metadata:
      labels:
        app: authentication
    spec:
      nodeSelector:
        node-type: services  # Bu node label'ı
      containers:
        - name: authentication
          image: 708778582346.dkr.ecr.us-east-1.amazonaws.com/authentication-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000