apiVersion: v1
kind: Namespace
metadata:
  name: gitops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: gitops
  labels:
    app: argocd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-server
  template:
    metadata:
      labels:
        app: argocd-server
    spec:
      containers:
      - name: argocd-server
        image: argoproj/argocd:latest
        command:
        - argocd-server
        - --insecure
        ports:
        - containerPort: 8080
        - containerPort: 8081
        - containerPort: 8082
        env:
        - name: ARGOCD_API_SERVER_REPLICAS
          value: "1"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: gitops
  labels:
    app: argocd-server
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 8080
    protocol: TCP
    name: https
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: grpc
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: metrics
  selector:
    app: argocd-server
---
