name: S3 CFN Deploy & Individual Upload

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::708778582346:role/onur-github-role
          aws-region: us-east-1

      - name: Deploy S3 CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation_templates/s3.yml \
            --stack-name s3-bucket-stack \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Retrieve Bucket Name
        id: get-bucket
        run: |
          BUCKET=$(aws cloudformation describe-stacks \
            --stack-name s3-bucket-stack \
            --query "Stacks[0].Outputs[?OutputKey=='BucketName'].OutputValue" \
            --output text)
          echo "bucket=$BUCKET" >> $GITHUB_OUTPUT

      - name: Upload files individually to S3
        run: |
          cd $GITHUB_WORKSPACE
          # $BUCKET değişkenini aşağıdaki şekilde kullanıyoruz
          for file in $(find . -type f \
            ! -path "./.git/*" \
            ! -path "./.github/*" \
            ! -path "*/Macos/*" \
            ! -path "*/Git/*" \
            ! -name ".DS_Store" \
            | sed 's|^\./||'); do
            echo "Uploading $file..."
            aws s3 cp "$file" "s3://${{ steps.get-bucket.outputs.bucket }}/$file"
          done
