# .github/workflows/csv-only-upload.yml
name: S3 CFN Deploy & CSV Upload

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-and-upload-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Fetch and checkout all LFS objects
        run: |
          git lfs install --local
          git lfs fetch --all
          git lfs checkout

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::708778582346:role/onur-github-role
          aws-region: us-east-1

      - name: Deploy S3 CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation_templates/s3.yml \
            --stack-name s3-bucket-stack \
            --region us-east-1 \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Retrieve Bucket Name
        id: get-bucket
        run: |
          echo "bucket=$(aws cloudformation describe-stacks \
            --stack-name s3-bucket-stack \
            --region us-east-1 \
            --query \"Stacks[0].Outputs[?OutputKey=='BucketName'].OutputValue\" \
            --output text)" >> $GITHUB_OUTPUT

      - name: Upload only CSV files to S3
        run: |
          BUCKET=${{ steps.get-bucket.outputs.bucket }}
          echo "Uploading CSV files to s3://$BUCKET/"
          find . -type f -iname '*.csv' \
            ! -path "./.git/*" \
            ! -path "./.github/*" \
            ! -path "*/Macos/*" \
            ! -path "*/Git/*" \
          | sed 's|^\./||' \
          | while read file; do
              echo "→ $file"
              aws s3 cp "$file" "s3://$BUCKET/$file"
            done
