# .github/workflows/s3-deploy-sync.yml
name: S3 CFN Deploy & Sync All

on:
  workflow_dispatch:

permissions:
  id-token: write   # OIDC token izni
  contents: read    # kodu checkout edebilmek için

jobs:
  deploy-and-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with LFS)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # tam geçmiş
          lfs: true        # LFS objelerini indir

      - name: Pull LFS files
        run: git lfs checkout

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::708778582346:role/onur-github-role
          aws-region: eu-central-1

      - name: Deploy S3 CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation_templates/s3.yml \
            --stack-name s3-bucket-stack \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Retrieve Bucket Name
        id: get-bucket
        run: |
          echo "bucket=$(aws cloudformation describe-stacks \
            --stack-name s3-bucket-stack \
            --query \"Stacks[0].Outputs[?OutputKey=='BucketName'].OutputValue\" \
            --output text)" >> $GITHUB_OUTPUT

      - name: Sync all files to S3
        run: |
          aws s3 sync . s3://${{ steps.get-bucket.outputs.bucket }} \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*"
